# Generated by Django 3.1.5 on 2021-05-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210509_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='name',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('hard', 'hard'), ('medium', 'medium'), ('easy', 'easy')], max_length=6),
        ),
    ]
